### ISSUE TITLE
can not resume a suspended server

### ISSUE THREAD

**Issue by xsunsmile** [makern/knife-vagrant2#6]
```
bundle exec knife vagrant server list
Instance Name  IP Address    Box                        Provider       State    
test           192.168.67.2  opscode-centos-fusion-6.5  vmware_fusion  suspended
```

```
bundle exec knife vagrant server resume test
ERROR: Instance test needs to be suspended for resume. Current state is suspended
```

https://github.com/makern/knife-vagrant2/blob/master/lib/chef/knife/vagrant_server_resume.rb#L22, should we check 

```
state == 'saved' or statet == 'suspended'?
```

**Comment by makern** [comment]
This is tricky to solve properly because vagrant doesn't normalize the status returned by the providers. I couldn't even find a comprehensive list of statuses for virtualbox when I wrote the original code.

The proper solution would be to parse the provider out of the vagrant file and have normalization tables in knife-vagrant2 itself. I don't think that's worth the effort though.

Lets go with the solution you proposed and just check for both but add a comment that one is for virtualbox and the other for vmware. Would you mind sending a pull request for that? :)
